### ISSUE TITLE
Thor parser

### ISSUE THREAD

**Issue by LimeEng** [MartinMSPedersen/othello-games#1]
Hello!

Do you still have access to the parser you used to convert between the Thor and PGN format and if so, would you consider uploading it here? It would be a great resource which would make it easier to convert to other custom formats.

Grateful for any answers!

**Comment by MartinMSPedersen** [comment]
Sure. I have it somewhere and I will try to locate it. Currently I don't need remember which language was used to write the converter.

**Comment by MartinMSPedersen** [comment]
Here is a link to the conversion part. It is written in R and it currently outputs XOR-format. I think I wrote some basic AWK to convert the XOR to json afterwards.

I will soon rewrite it everything in C so it will more portable.
[thor2xor.R](https://gist.github.com/MartinMSPedersen/8a50a06fb4e14a9bf56e5f35be32ada8)

**Comment by LimeEng** [comment]
That is amazingly helpful, thank you for your quick response!
